In [ ]:
!pip install Kaggle

In [ ]:

# !mkdir C:/Users/ADITYA/.kaggle
# !mv kaggle.json C:/Users/ADITYA/.kaggle/
!chmod 600 C:/Users/ADITYA/.kaggle

chmod: cannot access 'C:/Users/ADITYA/.kaggle': No such file or directory


In [ ]:
import os
import zipfile
import numpy as np
import cv2
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from kaggle.api.kaggle_api_extended import KaggleApi
from google.colab import files

# Upload kaggle.json
uploaded = files.upload()

# Move kaggle.json to the appropriate directory
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json # Set appropriate permissions

# Authenticate with Kaggle API
api = KaggleApi()
api.authenticate()

# Download dataset
dataset_name = 'chetankv/dogs-cats-images'
api.dataset_download_files(dataset_name, unzip=False)

# Extract dataset
with zipfile.ZipFile(f"{dataset_name.split('/')[1]}.zip", 'r') as zip_ref:
    zip_ref.extractall('dogs_cats_dataset')  # Extract to 'dogs_cats_dataset' folder

# Function to load and preprocess images
def load_data(directory):
    images = []
    labels = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.jpg'):
                img_path = os.path.join(root, file)
                label = 0 if 'cat' in file else 1  # 0 for cats, 1 for dogs
                image = cv2.imread(img_path)
                image = cv2.resize(image, (64, 64))  # Resize images to a standard size
                images.append(image)
                labels.append(label)
    return np.array(images), np.array(labels)

# Load dataset
cats_data, cats_labels = load_data('dogs_cats_dataset/dataset/training_set/cats')
dogs_data, dogs_labels = load_data('dogs_cats_dataset/dataset/training_set/dogs')

# Combine data and labels
X = np.concatenate((cats_data, dogs_data))
y = np.concatenate((cats_labels, dogs_labels))

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Flatten images for SVM input (convert to 1D)
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

# Train SVM
svm = SVC(kernel='linear')
svm.fit(X_train_flat, y_train)

# Predictions
y_pred = svm.predict(X_test_flat)

# Evaluation
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

print("Support Vectors:\n", svm.support_vectors_)
print("Number of Support Vectors for each class:", svm.n_support_)
print("Indices of Support Vectors:", svm.support_)
print("Coefficients of the support vector in the decision function:", svm.dual_coef_)
print("Intercept (bias) of the decision function:", svm.intercept_)

Saving dogs-cats-images-metadata.json to dogs-cats-images-metadata (1).json
mv: cannot stat 'kaggle.json': No such file or directory
Dataset URL: https://www.kaggle.com/datasets/chetankv/dogs-cats-images
              precision    recall  f1-score   support

           0       0.54      0.56      0.55       804
           1       0.54      0.52      0.53       796

    accuracy                           0.54      1600
   macro avg       0.54      0.54      0.54      1600
weighted avg       0.54      0.54      0.54      1600

Accuracy: 0.538125


In [ ]:
import os
import zipfile
import numpy as np
import cv2
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from kaggle.api.kaggle_api_extended import KaggleApi
from google.colab import files

# Upload kaggle.json
uploaded = files.upload()

# Move kaggle.json to the appropriate directory
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json # Set appropriate permissions

# Authenticate with Kaggle API
api = KaggleApi()
api.authenticate()

# Download dataset
dataset_name = 'chetankv/dogs-cats-images'
api.dataset_download_files(dataset_name, unzip=False)

# Extract dataset
with zipfile.ZipFile(f"{dataset_name.split('/')[1]}.zip", 'r') as zip_ref:
    zip_ref.extractall('dogs_cats_dataset')  # Extract to 'dogs_cats_dataset' folder

# Function to load and preprocess images
def load_data(directory):
    images = []
    labels = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.jpg'):
                img_path = os.path.join(root, file)
                label = 0 if 'cat' in file else 1  # 0 for cats, 1 for dogs
                image = cv2.imread(img_path)
                image = cv2.resize(image, (64, 64))  # Resize images to a standard size
                images.append(image)
                labels.append(label)
    return np.array(images), np.array(labels)

# Load dataset
cats_data, cats_labels = load_data('dogs_cats_dataset/dataset/training_set/cats')
dogs_data, dogs_labels = load_data('dogs_cats_dataset/dataset/training_set/dogs')

# Combine data and labels
X = np.concatenate((cats_data, dogs_data))
y = np.concatenate((cats_labels, dogs_labels))

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Flatten images for SVM input (convert to 1D)
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

# Train SVM
svm = SVC(kernel='linear')
svm.fit(X_train_flat, y_train)

# Predictions
y_pred = svm.predict(X_test_flat)

# Evaluation
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

print("Support Vectors:\n", svm.support_vectors_)
print("Number of Support Vectors for each class:", svm.n_support_)
print("Indices of Support Vectors:", svm.support_)
print("Coefficients of the support vector in the decision function:", svm.dual_coef_)
print("Intercept (bias) of the decision function:", svm.intercept_)

Saving dogs-cats-images-metadata.json to dogs-cats-images-metadata (2).json
mv: cannot stat 'kaggle.json': No such file or directory
Dataset URL: https://www.kaggle.com/datasets/chetankv/dogs-cats-images
              precision    recall  f1-score   support

           0       0.54      0.56      0.55       804
           1       0.54      0.52      0.53       796

    accuracy                           0.54      1600
   macro avg       0.54      0.54      0.54      1600
weighted avg       0.54      0.54      0.54      1600

Accuracy: 0.538125
Support Vectors:
 [[ 62.  36.  19. ... 189. 174. 155.]
 [197. 196. 191. ... 186. 192. 188.]
 [  3.   6.  11. ...  64.  52.  43.]
 ...
 [ 39.  31.  38. ...  83.  90.  90.]
 [164. 164. 164. ... 119. 125. 128.]
 [159. 169. 169. ...  45.  56.  54.]]
Number of Support Vectors for each class: [1882 2100]
Indices of Support Vectors: [   0    3    8 ... 6395 6396 6399]
Coefficients of the support vector in the decision function: [[-3.61288442e-06 -2.8044